DBUSER="storiaadmin"
DBPASSWD="zunSTjQ72GWzUzz"
#DBPASSWD="3ip0iN47kKHyRIo"
AppDBHOST="rrapp.prod.storia.vsapplications.com"
AdminDBHOST="rradmin.prod.storia.vsapplications.com"
AuthDBHOST="rrauth.prod.storia.vsapplications.com"
DicDBHOST="rrdictionary.prod.storia.vsapplications.com"
EntDBHOST="rrentitlement.prod.storia.vsapplications.com"
LogDBHOST="dblogmonitor.prod.storia.vsapplications.com"
DataDBHOST="rrdata.prod.storia.vsapplications.com"
AppDATABASE="dbstoriaapp"
AdminDATABASE="dbstoriaadmin"
AuthDATABASE="dbstoriaauth"
DicDATABASE="dbstoriadictionary"
EntDATABASE="dbstoriaentitlement"
LogDATABASE="bstorialogmonitor"
DataDATABASE="dbstoriaanalytics"
S3bucket="caching-bucket"


