DBUSER="storiaadmin"
DBPASSWD="3ip0iN47kKHyRIo"
AppDBHOST="rrapp.dev.storia.vsapplications.com"
AdminDBHOST="rradmin.dev.storia.vsapplications.com"
AuthDBHOST="rrauth.dev.storia.vsapplications.com"
DicDBHOST="rrdictionary.dev.storia.vsapplications.com"
EntDBHOST="rrentitlement.dev.storia.vsapplications.com"
LogDBHOST="dblogmonitor.dev.storia.vsapplications.com"
DataDBHOST="rrdata.dev.storia.vsapplications.com"
AppDATABASE="dbstoriaapp"
AdminDATABASE="dbstoriaadmin"
AuthDATABASE="dbstoriaauth"
DicDATABASE="dbstoriadictionary"
EntDATABASE="dbstoriaentitlement"
LogDATABASE="bstorialogmonitor"
DataDATABASE="dbstoriaanalytics"
S3bucket="caching-bucket"


